platform :ios, '8.0'
use_frameworks!
target 'WZWeather' do
pod 'AFNetworking', '~> 2.6'
pod 'MJRefresh', '~> 3.1.12'
pod 'IQKeyboardManager', '~> 4.0.8'
pod 'GPUImage', '~> 0.1.7'
pod 'Masonry'
pod 'SDWebImage'
pod 'SVProgressHUD'
end
